### PR TITLE
WIP: Feature/rt-n65u

### LINKED ISSUE #63: Add support for RT-N65U back
Isn't possible to revert this commit https://github.com/Linaro1985/padavan-ng/commit/cc59635a2bbda0b13a6e8b087b2e351cbdbb09ba and bring RT-N65U support back?
I have already ported kernel config to 3.4.x locally.

### PR DESCRIPTION
**Pull request by andy9a9**
- Bring support for ASUS RT-N65U back
  - port kernel config to 3.4.x
- port rt3352 wifi driver for second interface
  - use rt2860v2 as template
 - add missing include of interrupt header

WIP: needs to be clarified if it's working directly on device

Closes #63

### CODE REVIEW

**Comment by Linaro1985** [comment]
Hi. Are you tested this on real device?

**Comment by andy9a9** [comment]
Hi, not yet.
This is the reason, why I am keeping it as WIP. I am going to test it during weekend.

**Comment by andy9a9** [comment]
Device is not booting...
```
Starting kernel ...


LINUX started...
Linux version 3.4.113 (padavan@hms) (gcc version 7.4.0 (crosstool-NG UNKNOWN) ) #1 Fri May 24 13:08:47 EDT 2019
Ralink SoC: RT3883, RevID: 0105, RAM: DDR2, XTAL: 40MHz
CPU/OCP/SYS frequency: 500/166/166 MHz
CPU revision is: 0001974c (MIPS 74Kc)
Determined physical RAM map:
 memory: 08000000 @ 00000000 (usable)
Zone PFN ranges:
  Normal
0x00000000 -> 0x00008000
Movable zone start PFN for each node
Early memory PFN ranges
    0: 0x00000000 -> 0x00008000
Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
Built 1 zonelists in Zone order, mobility grouping on. Total pages: 32512
Kernel command line: console=ttyS0,115200n8
PID hash table entries: 512 (order: -1, 2048 bytes)
Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
Writing ErrCtl register=00000000
Readback ErrCtl register=00000000
Memory: 126356k/131072k available (2788k kernel code, 4716k reserved, 455k data, 208k init, 0k highmem)
NR_IRQS:40
console [ttyS0] enabled
Calibrating delay loop... 249.34 BogoMIPS (lpj=498688)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 512
NET: Registered protocol family 16
bio: create slab <bio-0> at 0
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
PCI host bridge to bus 0000:00
pci_bus 0000:00: root bus resource [mem 0x20000000-0x2fffffff]
pci_bus 0000:00: root bus resource [io  0x10160000-0x1016ffff]
pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
pci 0000:00:00.0: BAR 8: assigned [mem 0x20000000-0x200fffff]
pci 0000:00:00.0: BAR 1: assigned [mem 0x20100000-0x2010ffff]
pci 0000:01:00.0: BAR 0: assigned [mem 0x20000000-0x20007fff 64bit]
pci 0000:00:00.0: PCI bridge to [bus 01-01]
pci 0000:00:00.0:   bridge window [mem 0x20000000-0x200fffff]
PCI: Enabling device 0000:00:00.0 (0000 -> 0002)
Switching to clocksource MIPS
NET: Registered protocol family 2
IP route cache hash table entries: 1024 (order: 0, 4096 bytes)
TCP established hash table entries: 4096 (order: 3, 32768 bytes)
TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
TCP: Hash tables configured (established 4096 bind 4096)
TCP: reno registered
UDP hash table entries: 256 (order: 0, 4096 bytes)
NET: Registered protocol family 1
squashfs: version 4.0 (2009/01/31) Phillip Lougher
msgmni has been set to 246
io scheduler noop registered (default)
Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
serial8250: ttyS0 at MMIO 0x10000c00 (irq = 20) is a 16550A
Ralink GPIO driver initialized. Number of GPIO: 96, GPIO mode: 000018DD
loop: module loaded
Ralink SPI flash driver, SPI clock: 41MHz
unrecognized SPI chip ID: 61 (100c6110), please update the SPI driver!
SPI flash chip: Unknown (00 ffffffff) (16384 Kbytes)
raspi: error parsing Firmware partition
tun: Universal TUN/TAP device driver, 1.6
tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
Ralink APSoC Ethernet Driver v3.2.4 (raeth)
raeth: PDMA RX ring 256, PDMA TX ring 512. Max packet size 1536
raeth: Byte Queue Limits (BQL) support
PPP generic driver version 2.4.2
PPP MPPE Compression module registered
NET: Registered protocol family 24
PPTP driver version 0.8.5
Realtek RTL8367RB GSW Driver v3.1.
rtl8367 - hw bridge: W|LLLL
usbcore: registered new interface driver libusual
nf_conntrack version 0.5.0 (16384 buckets, 32768 max)
xt_time: kernel timezone is -0000
Bridge firewalling registered
gre: GRE over IPv4 demultiplexor driver
ip_tables: (C) 2000-2006 Netfilter Core Team
TCP: cubic registered
NET: Registered protocol family 10
ip6_tables: (C) 2000-2006 Netfilter Core Team
IPv6 over IPv4 tunneling driver
NET: Registered protocol family 17
L2TP core driver, V2.0
PPPoL2TP kernel driver, V2.0
8021q: 802.1Q VLAN Support v1.8
ASUS NVRAM, v0.08. Available space: 61440. Integrity: MTD is empty
VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
Please append a correct "root=" boot option; here are the available partitions:
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
```
Now I have to check, what could be wrong...

**Comment by andy9a9** [comment]
Ok, device is now booting as well, but there is a problem with 2.4GHz wifi.
```
rc notification: control_wifi_guest_wl_off
rc notification: control_wifi_radio_wl_on
validate_asp_apply(0x0466): debug restart_needed_bits: 0x1000
validate_asp_apply(0x0466): debug restart_needed_bits: 0x1000
validate_asp_apply(0x0466): debug restart_needed_bits: 0x1000
ej_notify_services(0x0551): debug restart_needed_bits before: 0x1000
event signal: User defined signal 1
rc notification: restart_wifi_rt
ej_notify_services(0x058b): debug restart_needed_bits after: 0x0
rtl8367 - iNIC isolation: 1
rtl8367 - iNIC port link: 1
rtl8367 - iNIC isolation: 0
/sys/class/net/ra1/brport/isolate_mode: No such file or directory
/sys/class/net/eth2.3/brport/isolate_mode: No such file or directory
```

**Comment by andy9a9** [comment]
Hi @Linaro1985 !

Can we live with disabled 2.4GHz wifi, if I won't be able to fix it?

**Comment by Simonmicro** [comment]
@andy9a9 At least we place put a huge warning on the dashboard, so nobody wonders why AND should have the ability to downgrade to the last stable version. Anyway - by upgrading the kernel: Have we altered the driver for the 2.4GHz module -> maybe we could try to port the old driver for the new kernel...

**Comment by andy9a9** [comment]
As I have already wrote, I am trying to compile the driver from scratch based on rt2860v2. Because the previous version was only binary (iNIC_mii_asus.obj - https://github.com/andy-padavan/rt-n56u/commit/7f0571b2e15622d35296ab00d08fca4f9818d389) and I don't know, which sources have been used for compilation.

**Comment by andy9a9** [comment]
I have made some progress here, but I think with not the right way.
- ported drivers from rt2860v2
  - missing support for MII
    - sources are based on rtsoc/PCI BUS, but RT3352 @2.4GHz is based on MII BUS
- iINIC_mii binary blob
 - binary is not compatible with kernel 3.4.x
   - I have modified skbuff to make some functions public, which this blob requires
   - I have ported some required conditional-compilation flags
     - compilation was successful, but kernel hanged up after trying to load this module
   - without sources is only guessing what is wrong

Summ-up:
- device is working without 2.4GHz support as well
  - missing sources
- If you are ok, that we will support only 5GHz wifi, I can write some comment into device template.
- If not, I will make my own fork and disable 2.4GHz anyway. I don't need this wifi support.

Please let me know, if I make this PR ready for review or close it.

**Pull request closed without merging**
